import Foundation
import AppKit
import ScannerKit
import MemoryKit
import BatteryKit
import ThermalKit
import LedgerKit

/// Assembles every organ's honest numbers into one paste-able snapshot — the
/// "help, my Mac is acting up" artifact, in Stockpile's voice: both truths,
/// purgeable and cached explained, nothing dressed up.
enum SystemReport {
    static func build(reclaimable: Int64) async -> String {
        var lines: [String] = ["# Stockpile system report", ""]

        if let disk = try? DiskAccounting.measure() {
            lines += [
                "## Disk",
                "- Physical used: \(disk.physicalUsed.bytesFormatted) (\(pct(disk.physicalUsedFraction))) — the real bytes",
                "- Effective used: \(disk.effectiveUsed.bytesFormatted) (\(pct(disk.effectiveUsedFraction))) — after purgeable",
                "- Purgeable: \(disk.purgeable.bytesFormatted) — macOS auto-reclaims this",
                "- Reclaimable by Stockpile: \(reclaimable.bytesFormatted)",
                "",
            ]
        }

        if let mem = MemoryMonitor().read() {
            lines += [
                "## Memory (\(mem.pressureHeadline))",
                "- Genuinely in use: \(mem.used.bytesFormatted) of \(mem.total.bytesFormatted) — honest",
                "- Naive \"used\": \((mem.total - mem.free).bytesFormatted) — counts cached files",
                "- Available: \(mem.available.bytesFormatted) (free + evictable cache)",
                "",
            ]
        }

        let heat = await ThermalMonitor().sample()
        let ownPID = ProcessInfo.processInfo.processIdentifier
        let top = heat.processes.filter { $0.pid != ownPID }.prefix(3)
        lines += ["## Heat (\(heat.level.headline))"]
        for p in top {
            lines.append("- \(p.command): \(pct(heat.share(of: p))) of active load (\(Int(p.cpuPercent))% CPU)")
        }
        lines.append("")

        if let bat = BatteryMonitor().read() {
            lines += [
                "## Battery (\(bat.healthHeadline))",
                "- Health: \(bat.healthPercent)% — holds \(bat.maxCapacity) of \(bat.designCapacity) mAh",
                "- Charge: \(bat.charge)% · \(bat.cycleCount) cycles",
                "",
            ]
        }

        lines += ["_Generated by Stockpile — both truths, purgeable & cached explained, no marketing math._"]
        return lines.joined(separator: "\n")
    }

    static func copyToClipboard(_ text: String) {
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(text, forType: .string)
    }

    private static func pct(_ f: Double) -> String {
        f.formatted(.percent.precision(.fractionLength(0)))
    }
}
